### ISSUE TITLE
reported shift 

### ISSUE THREAD

**Issue by sgascoin** [CNES/demcompare#3]
I think that in the output log the reported "Planimetry 2D shift between DEM and REF" should be multiplied by the pixel size (or remove the meter unit)
 -> row : xx m
 -> col : yy m

**Comment by duboise-cnes** [comment]
Hello @sgascoin , thanks for the comment ! We are currently developing a refactor version of demcompare and I am reporting this remark in the list for next release. 
Don't hesitate if you have other remarks, following the internal refactoring, we will try to change/clean the global output of demcompare to be more adequate for users (command line output logs and report)

**Comment by sgascoin** [comment]
ok great! If I may.. A very useful feature would be the possibility to apply a mask to exclude some areas of the DEM in the coregistration process. Ideally this mask could be a shapefile or a raster in any reference system (demcompare would handle the reprojection to the DEM grid..).

**Comment by duboise-cnes** [comment]
Hello, the last demcompare version 0.5.0 (with new API) is published just now. The bug should be fixed in this version. 

I report the proposal in future possible features, thanks for the comment. 

Can you tell me if I can close this issue ? 
Hoping that this new version cope with your needs to compare DEM. 

Cordially.
